
development:
  adapter: postgresql
  database: airbnb_clone_development
test:
  adapter: postgresql
  database: airbnb_clone_test
production:
  adapter: postgresql
  encoding: unicode
  database: trash_production
  pool: 5
  username: trash
  password:
